### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by tul4ins** [bobiboMC/Automatic-Appointment-MyVisit#1]
Is the service still running?
I installed all libraries according to the instructions. Addititionally i installed audio_speech_to_text.py, request_audio.py and change numer telephone in main.py. But i have an error, when i start main.py
`C:\Job\Docs\python_env\mlc_env>python main.py
Traceback (most recent call last):
  File "C:\Job\Docs\python_env\mlc_env\main.py", line 119, in <module>
    driver = uc.Chrome(options=options,service_creationflags=subprocess.CREATE_NO_WINDOW)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 431, in __init__
    service = selenium.webdriver.common.service.Service(
TypeError: Can't instantiate abstract class Service with abstract method command_line_args`

**Comment by bobiboMC** [comment]
What version of `undetected_chromedriver` package do you have?
When I run my code,I run it with `Version: 3.1.7` without any problems.

**Comment by tul4ins** [comment]
undetected-chromedriver 3.4.6
selenium                4.8.2

**Comment by bobiboMC** [comment]
First of all,try to use selenium `Version: 4.5.0` and undetected-chromedriver `Version: 3.1.7`,maybe something crucial was changed in the following versions of these packages.
